# Generated by Django 5.1.1 on 2024-09-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
