# Generated by Django 5.1.1 on 2024-09-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
    ]
