# Generated by Django 5.1.1 on 2024-09-29 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_advertisement_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='date_finish',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 23, 41, 50, 710558)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 23, 41, 50, 710341)),
        ),
    ]
