# Generated by Django 5.1.1 on 2024-10-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0014_alter_advertisement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='Проект_2024-10-03 02:06:32.733040', max_length=60),
        ),
    ]
