# Generated by Django 5.1.1 on 2024-10-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0016_alter_advertisement_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='id_adv',
            new_name='adv_id',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status_first_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status_done',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='Проект_2024-10-03 20:32:59.288990', max_length=60),
        ),
    ]
