# Generated by Django 5.1.1 on 2024-10-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0017_rename_id_adv_advertisement_adv_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='Проект_2024-10-03 22:18:20.763201', max_length=60),
        ),
    ]
