# Generated by Django 5.1.1 on 2024-09-30 01:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_alter_advertisement_date_finish_and_more'),
        ('connect_api_second_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='key_adv',
        ),
        migrations.RemoveField(
            model_name='product',
            name='key_adv',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='key_adv',
        ),
        migrations.AlterField(
            model_name='industry',
            name='id_industry',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='advertisement.advertisement'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='advertisement.advertisement'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id_provider',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='advertisement.advertisement'),
        ),
    ]
