# Generated by Django 5.1.1 on 2024-10-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_api_second_server', '0002_remove_industry_key_adv_remove_product_key_adv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='id_industry',
            new_name='adv',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_product',
            new_name='adv',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='id_provider',
            new_name='adv',
        ),
    ]
