# Generated by Django 5.1.1 on 2024-10-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_api_second_server', '0003_rename_id_industry_industry_adv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='founding_date',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='skill_level',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='text_out',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_out',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='text_out',
            field=models.TextField(blank=True),
        ),
    ]
