# Generated by Django 5.1.1 on 2024-10-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_api_second_server', '0004_industry_founding_date_product_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='founding_date',
            field=models.CharField(blank=True, default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='provider',
            name='skill_level',
            field=models.TextField(blank=True, default=None),
        ),
    ]
